# Change these first
owner: tiarebalbi # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Manual do Terapeuta - Website
    url: https://portal.manualdoterapeuta.com.br/
  - name: Manual do Terapeuta - API
    url: https://api.manualdoterapeuta.com.br/actuator/info

status-website:
#  cname: monitor.manualdoterapeuta.com.br
  baseUrl: /uptime-monitor
  apiBaseUrl: https://api.github.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Manual do Terapeuta
  introTitle: "**MTS** Monitoramento do Serviços"
  introMessage: "Olá, bem vindo ao **MTS**. Aqui você pode ver o status dos serviços que utilizamos."
  navbar:
    - title: Status
      href: /
    - title: Portal MTS
      href: https://portal.manualdoterapeuta.com.br/
